project:
  type: website
  resources:
    - resources/
  render:
    - "*.qmd"
  output-dir: "docs"
website:
  title: ""
  site-url: https://conclat.com/
  description: "Fondecyt Clases, Trabajo y Conflicto"
  favicon: resources/img/conclat_ID_principal_rojo.png
  search: true
  repo-url: https://github.com/DaniOlivaresCollio/conclat-web
  page-footer:
    background: "#121212"
    left: |
      [2025]()
    center:
      - href: https://github.com/DaniOlivaresCollio/conclat-web
        icon: github
        aria-label: GitHub
    right: |
       Last Update: {{< modified isodate>}}
  navbar:
    logo: resources/img/conclat_ID_principal_rojo.png
    background: "#FFFFFF"
    tools: 
       - icon: github
         href: https://github.com/DaniOlivaresCollio/conclat-web
       - icon: instagram
         href: https://www.instagram.com/proyecto.conclat/  
    # pinned: true
    left:
      - text: Sobre CONCLAT
        icon: info-square-fill
        href: informacion/01-sobre.qmd
      - text: Nosotros
        icon: people-fill
        href: nosotros/nosotros.qmd
      - text: Encuesta
        icon: list-ul
        menu: 
         - href: encuesta/01-chile/
           text: "{{<ai list-ul>}} Encuesta Chile"
         - href: encuesta/02-argentina/
           text: "{{<ai list-ul>}} Encuesta Argentina"
      - text: Investigaci√≥n
        icon: journals
        href: investigacion/investigacion.qmd
      - text: Prensa
        icon: newspaper
        href: recomendados/recomendados.qmd
      - text: Actividades
        icon: calendar-week
        href: actividades/actividades.qmd
      - text: Contacto
        icon: envelope
        href: contacto/contacto.qmd
     
format:
  html:
    theme: 
      light: flatly
    css: 
      - styles.css
      - resources/css/home.css
    linkcolor: "#CA0000"
    include-after-body: 
      - footer/footer.html
      - resources/js/particles-init.html